// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://midklxglczcqtjkotgpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZGtseGdsY3pjcXRqa290Z3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjYzNTMsImV4cCI6MjA2MjA0MjM1M30.X9tFuoBmOMngZdQgMr02m84N3hE2f4XwrFijjhhqO9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);